export const AllMeasurements = [
  {
    type: "Paint",
    details: [
      "Waist",
      "Seat",
      "Calf/Knee",
      "Bottom/Bells",
      "Lenght",
      "Fly/Ply",
    ],
  },
  {
    type: "Shirt",
    details: [
      "Lenght",
      "Neck",
      "Shoulder",
      "Chest",
      "Waist",
      "Seat",
      "Sleeves",
      "Sleeve Circum (All Around)",
    ],
  },
  {
    type: "Shorts",
    details: [
      "Waist",
      "Seat",
      "Calf/Knee",
      "Bottom/Bells",
      "Lenght",
      "Fly/Ply",
    ],
  },
  {
    type: "Churidar",
    details: [
      "Lenght",
      "Neck",
      "Shoulder",
      "Upper Chest (All Around)",
      "Bust (All Around)",
      "Waist (All Around)",
      "Seat (All Around)",
      "Armhole (All Around)",
      "Sleeve Lenght",
      "Sleeve Circum (All Around)",
      "Front Neck Depth",
      "Back Neck Depth",
      "Bottom's Length",
      "Bottoms Waist (All Around)",
      "Bottoms Hip (All Around)",
      "Knee/Calf (All Around)",
      "Ankle (All Around)",
    ],
  },
];
